# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Alexander Mohr

[package]
name = "mdd-core"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
cda-database = { git = "https://github.com/eclipse-opensovd/classic-diagnostic-adapter.git", rev = "c1c9db5c9b95b790fa3e905ac1c04d38880a532e" }
cda-interfaces = { git = "https://github.com/eclipse-opensovd/classic-diagnostic-adapter.git", rev = "c1c9db5c9b95b790fa3e905ac1c04d38880a532e" }

# Error handling
anyhow = "1"

# Serialization (for Tauri command return types)
serde = { version = "1", features = ["derive", "rc"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
similar_names = "allow"
clone_on_ref_ptr = "warn"
indexing_slicing = "deny"
unwrap_used = "deny"
arithmetic_side_effects = "deny"
separated_literal_suffix = "deny"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(nightly)'] }
